---
title: "looking_at_significance"
output:
  workflowr::wflow_html:
    code_folding: hide
    toc: no
  html_notebook: default
  html_document:
    df_print: paged
    toc: no
editor_options:
  chunk_output_type: console
---

## Introduction



```{r setup, include=FALSE}
knitr::opts_chunk$set(cache= TRUE)
knitr::opts_chunk$set(autodep = TRUE)
library("rmeta")
```

```{r load.data}
setwd('~/lipids_mvp/analysis/')
mash=readRDS("../data/mashcomplete.rds")
ash=readRDS("../data/ash.rds")
bf=read.table('../data/merged_betas.txt')
sf=read.table('../data/merged_se.txt')
z=read.table("../data/merged_z.txt")
pm=mash$result$PosteriorMean
pv=mash$result$PosteriorSD
lfsr=mash$result$lfsr
rownames(lfsr)=bf$SNP_hg18[1:2437099]
betas=bf[1:2437099,c("hdl","ldl","tg","tc")];rownames(betas)=bf$SNP_hg18[1:2437099]
se=sf[1:2437099,c("hdl","ldl","tg","tc")];rownames(se)=sf$SNP_hg18[1:2437099]

shrunk.beta=se*pm;colnames(shrunk.beta)=colnames(pm);rownames(shrunk.beta)=rownames(betas)
shrunk.se=pv*se;colnames(shrunk.se)=colnames(pm);rownames(shrunk.se)=rownames(betas)
```


Let's print the maximum by hdl and then triglyceride:
```{r}

b=betas[order(abs(betas$hdl),decreasing=T),][1:100,]
tg=b[order(abs(b$tg),decreasing=T),][1:100,]

head(tg)
j=which(rownames(betas)==rownames(tg)[1])

# title=paste("MLE",bf[j,"rsid"])
# par(mfrow=c(1,2))
# metaplot(as.numeric(betas[j,]),as.numeric(se[j,]),colors=meta.colors(box=c("red","blue","green","yellow"),lines="blue", zero="red", summary="orange",text="forestgreen"),xlim=c(-0.4,0.4),labels = colnames(shrunk.beta),xlab = "",ylab="")
# title(title)


title=paste("Mash",bf[j,"rsid"])
sd=as.numeric(shrunk.se[j,])##to transform to posterior sd of beta
x=as.numeric(shrunk.beta[j,])
metaplot(x,sd,xlab = "",ylab="",colors=meta.colors(box=c("red","blue","green","yellow"),lines="blue", zero="red", summary="orange",text="forestgreen"),xlim=c(-0.4,0.4),labels = colnames(shrunk.beta))
title(title)

print("LFSR of SNP")
lfsr[j,]
```

We can do the same for LDL and TG, sorting first by LDL and then by TG

```{r}
b=betas[order(abs(betas$ldl),decreasing=T),][1:100,]
tg=b[order(abs(b$tg),decreasing=T),][1:100,]

head(tg)
j=which(rownames(betas)==rownames(tg)[1])

title=paste("MLE",bf[j,"rsid"])
par(mfrow=c(1,2))
metaplot(as.numeric(betas[j,]),as.numeric(se[j,]),colors=meta.colors(box=c("red","blue","green","yellow"),lines="blue", zero="red", summary="orange",text="forestgreen"),xlim=c(-0.4,0.4),labels = colnames(shrunk.beta),xlab = "",ylab="")
title(title)


title=paste("Mash",bf[j,"rsid"])
sd=as.numeric(shrunk.se[j,])##to transform to posterior sd of beta
x=as.numeric(shrunk.beta[j,])
metaplot(x,sd,xlab = "",ylab="",colors=meta.colors(box=c("red","blue","green","yellow"),lines="blue", zero="red", summary="orange",text="forestgreen"),xlim=c(-0.4,0.4),labels = colnames(shrunk.beta))
title(title)

print("LFSR of SNP")
lfsr[j,]
```


Let's tabulate bu LD block
```{r, eval=FALSE, echo=TRUE}

z=read.table("~/lipids_mvp/data/merged_z.txt")

bed=read.table("~/Downloads/ld_chunk.bed")

z=z[1:2437099,]### last 3 are rsIDs from mislabeled columns
library("reshape")
df=transform(z, foo = colsplit(z$SNP_hg18, split = "\\:", names = c('Chr', 'Pos')))

t=transform(rownames(lfsr), foo = colsplit(rownames(lfsr), split = "\\:", names = c('Chr', 'Pos')))

lfsr.mash=data.frame(t$foo.Chr,t$foo.Pos,lfsr,stringsAsFactors = T)

max_block=data.frame(matrix(ncol = 12,nrow=nrow(bed)))
colnames(lfsr.mash)=c("chr","pos","hdl","ldl","tg","tc")
for(i in 1:nrow(bed)){
 
  chr=bed[i,1]
  start=bed[i,2]
  stop=bed[i,3]
  in_chrom=lfsr.mash[lfsr.mash$chr==chr,]
  goodguys=in_chrom[in_chrom$pos>start&in_chrom$pos<stop,]

 if(nrow(goodguys)>0) {
    max_block[i,1]=goodguys[which.min(abs(goodguys[,"hdl"])),"hdl"]
   max_block[i,2]=as.character(goodguys[which.min(abs(goodguys[,"hdl"])),"chr"])
    max_block[i,3]=as.character(goodguys[which.min(abs(goodguys[,"hdl"])),"pos"])
    
   max_block[i,4]=goodguys[which.min(abs(goodguys[,"ldl"])),"ldl"]
      max_block[i,5]=as.character(goodguys[which.min(abs(goodguys[,"ldl"])),"chr"])
    max_block[i,6]=as.character(goodguys[which.min(abs(goodguys[,"ldl"])),"pos"])
    
      max_block[i,7]=goodguys[which.min(abs(goodguys[,"tg"])),"tg"]
      max_block[i,8]=as.character(goodguys[which.min(abs(goodguys[,"tg"])),"chr"])
    max_block[i,9]=as.character(goodguys[which.min(abs(goodguys[,"tg"])),"pos"])
    
 max_block[i,10]=goodguys[which.min(abs(goodguys[,"tc"])),"tc"]
      max_block[i,11]=as.character(goodguys[which.min(abs(goodguys[,"tc"])),"chr"])
    max_block[i,12]=as.character(goodguys[which.min(abs(goodguys[,"tc"])),"pos"])
    } else {
      z_good=rep(0,ncol(max_block))
    }
}

colnames(max_block)=c("hdl","chr","pos","ldl","chros","pos","tg","chr","pos","tc","chr","pos")

max_block=na.omit(max_block)

hdl=max_block[max_block$hdl<0.05,c(1:3)]

ldl=max_block[max_block$ldl<0.05,c(4:6)]

tg=max_block[max_block$tg<0.05,c(7:9)]

tc=max_block[max_block$tc<0.05,c(10:12)]

write.table(hdl,"../data/hdl_max.txt")


write.table(ldl,"../data/ldl_max.txt")

write.table(tg,"../data/tg_max.txt")

write.table(tc,"../data/tc_max.txt")
```

You can see the top snps per condition in hdl,ldl, tg and tc respectively:

```{r}
setwd("~/lipids_mvp/analysis/")

hdl=read.table("../data/hdl_max.txt")


ldl=read.table("../data/ldl_max.txt")

tg=read.table("../data/tg_max.txt")

tc=read.table("../data/tc_max.txt")

head(hdl)

head(ldl)

head(tg)

head(tc)
```