---
title: "LDL and TG Only"
output:
  workflowr::wflow_html:
    code_folding: hide
    toc: no
  html_notebook: default
  html_document:
    df_print: paged
    toc: no
editor_options:
  chunk_output_type: console
---

## Introduction


Here we consider the SNPS which are significant in only TG and LDL

```{r}

mash=readRDS("~/lipids_mvp/data/mashcomplete.rds")
tc=read.table("~/lipids_mvp/data//tc_max.txt")
tg=read.table("~/lipids_mvp/data//tg_max.txt")
hdl=read.table("~/lipids_mvp/data/hdl_max.txt")
ldl=read.table("~/lipids_mvp/data/ldl_max.txt")
bf=read.table("~/lipids_mvp/data/merged_betas.txt")[c(1:2437099),]
se=read.table("~/lipids_mvp/data/merged_se.txt")[c(1:2437099),]

z=read.table("~/lipids_mvp/data/merged_z.txt")[c(1:2437099),]
```

```{r}
ldl_tg=intersect(rownames(ldl),rownames(tg))## shared block significnat
a=ldl_tg[!(ldl_tg %in% rownames(hdl))]

pimat=matrix(mash$fitted_g$pi[-1],byrow = T,ncol=length(mash$fitted_g$Ulist))
barplot(colSums(pimat),names=names(mash$fitted_g$Ulist),las=2)

library(lattice)


clrs <- colorRampPalette(rev(c("#D73027","#FC8D59","#FEE090","#FFFFBF",
                               "#E0F3F8","#91BFDB","#4575B4")))(64)
i=2
lat=mash$fitted_g$Ulist[[i]]

colnames(lat)=rownames(lat)=colnames(se)[3:6]
lat[lower.tri(lat)] <- NA
print(levelplot(lat,col.regions = clrs,xlab = "",ylab = "",colorkey = TRUE,main=paste0(names(mash$fitted_g$Ulist)[[i]])))

i=3
lat=mash$fitted_g$Ulist[[i]]

colnames(lat)=rownames(lat)=colnames(se)[3:6]
lat[lower.tri(lat)] <- NA
print(levelplot(lat,col.regions = clrs,xlab = "",ylab = "",colorkey = TRUE,main=paste0(names(mash$fitted_g$Ulist)[[i]])))

i=4
lat=mash$fitted_g$Ulist[[i]]

colnames(lat)=rownames(lat)=colnames(se)[3:6]
lat[lower.tri(lat)] <- NA
print(levelplot(lat,col.regions = clrs,xlab = "",ylab = "",colorkey = TRUE,main=paste0(names(mash$fitted_g$Ulist)[[i]])))

 for(i in 2:4)
   {

lat=mash$fitted_g$Ulist[[i]]
s=svd(mash$fitted_g$Ulist[[i]])
colnames(s$v)=rownames(s$v)=colnames(se)[3:6]
barplot(s$v[,1],main=paste0(names(mash$fitted_g$Ulist)[[i]]))
}


df=cbind(ldl[a,],tg[a,])
#df=cbind(ldl[ldl_tg,],tg[ldl_tg,])
t=apply(df,1,function(x){x[3]==x[6]})##also shared position
ldl_tg_match=df[t,]


pm=mash$result$PosteriorMean
pv=mash$result$PosteriorSD
lfsr=mash$result$lfsr
rownames(pm)=bf$SNP_hg18[1:2437099]
rownames(se)=bf$SNP_hg18


shrunk.beta=se[,c(3:6)]*pm;colnames(shrunk.beta)=colnames(pm);
shrunk.se=pv*se[,c(3:6)];colnames(shrunk.se)=colnames(pm)

rownames(shrunk.beta)=rownames(shrunk.se)=rownames(pm)

sig=paste0(ldl_tg_match[,2],":",ldl_tg_match[,3])
good=shrunk.beta[sig,]
good.sd=shrunk.se[sig,]
```

```{r,eval=T}

rownames(bf)=rownames(shrunk.se)=rownames(shrunk.beta)=rownames(se)=rownames(lfsr)=bf$SNP_hg18
library('rmeta')

j=1
title=paste("MLE",bf[sig[j],"SNP_hg18"])
par(mfrow=c(1,2))
metaplot(as.numeric(z[sig[j],c(4,6,8,10)]),as.numeric(se[sig[j],c(3:6)]),colors=meta.colors(box=c("red","blue","green","yellow"),lines="blue", zero="red", summary="orange",text="forestgreen"),xlim=c(-0.4,0.4),labels = colnames(shrunk.beta),xlab = "",ylab="")
title(title)

title=paste("Mash",rownames(good)[j])
sd=as.numeric(pv[sig[j],])##to transform to posterior sd of beta
x=as.numeric(pm[sig[j],])
metaplot(x,sd,xlab = "",ylab="",colors=meta.colors(box=c("red","blue","green","yellow"),lines="blue", zero="red", summary="orange",text="forestgreen"),xlim=c(-0.4,0.4),labels = colnames(shrunk.beta))
title(title)

rbind(as.numeric(bf[sig[j],c(4,6,8,10)]),x)


lfsr[sig[j],]<0.05

pva=read.table("~/Dropbox/jointData/Ptable.txt")
rownames(pva)=pva$SNP_hg18

pva[sig[j],c(3:6)]<5e-8


j=1146823 
title=paste("MLE",bf[j,"SNP_hg18"])
par(mfrow=c(1,2))
metaplot(as.numeric(bf[j,c(4,6,8,10)]),as.numeric(se[j,c(3:6)]),colors=meta.colors(box=c("red","blue","green","yellow"),lines="blue", zero="red", summary="orange",text="forestgreen"),xlim=c(-0.4,0.4),labels = colnames(shrunk.beta),xlab = "",ylab="")
title(title)

title=paste("Mash",bf[j,"SNP_hg18"])
sd=as.numeric(shrunk.se[j,])##to transform to posterior sd of beta
x=as.numeric(shrunk.beta[j,])
metaplot(x,sd,xlab = "",ylab="",colors=meta.colors(box=c("red","blue","green","yellow"),lines="blue", zero="red", summary="orange",text="forestgreen"),xlim=c(-0.4,0.4),labels = colnames(shrunk.beta))
title(title)

rbind(as.numeric(bf[sig[j],c(4,6,8,10)]),x)


lfsr[sig[j],]<0.05
```
