---
title: "Sharing"
output:
  workflowr::wflow_html:
    code_folding: hide
    toc: no
  html_notebook: default
  html_document:
    df_print: paged
    toc: no
editor_options:
  chunk_output_type: console
---
```{r loaddata,echo=F}
setwd(("~/lipids_mvp/analysis/"))
library(gplots)
library(ggplot2)

library("data.table")

pm.mash=fread("~/Dropbox/post_means_mvp_for_ldpred.txt")
lfsr.all=readRDS("~/Dropbox/combined_shared_lfsr_mvp_mash_chr_bp.rds")





```

```{r generate matrix}
thresh=0.05

pm.mash.beta=pm.mash[rowSums(lfsr.all[,c(3:6)]<0.05)>0,]
lfsr.mash=lfsr.all[rowSums(lfsr.all[,c(3:6)]<0.05)>0,]

pm.mash.beta=data.frame(pm.mash.beta[,c("hdl","ldl","tg","tc")])
lfsr.mash=lfsr.mash[,c("hdl","ldl","tg","tc")]
shared.fold.size=matrix(NA,nrow = ncol(lfsr.mash),ncol=ncol(lfsr.mash))
colnames(shared.fold.size)=rownames(shared.fold.size)=colnames(lfsr.mash)
for(i in 1:ncol(lfsr.mash)){
  for(j in 1:ncol(lfsr.mash)){
    sig.row=which(lfsr.mash[,i]<thresh)
    sig.col=which(lfsr.mash[,j]<thresh)
    a=(union(sig.row,sig.col))
    #a=(intersect(sig.row,sig.col))
    #quotient=abs(pm.mash.beta[a,i]/pm.mash.beta[a,j])
    quotient=(pm.mash.beta[a,i]/pm.mash.beta[a,j])##divide effect sizes
    ##divide effect sizes
    shared.fold.size[i,j]=mean(quotient>0.5&quotient<2)
   
  }}

```





```{r heatmap2sharingmagnitude}


library(lattice)


clrs <- colorRampPalette(rev(c("#D73027","#FC8D59","#FEE090","#FFFFBF",
                               "#E0F3F8","#91BFDB","#4575B4")))(64)

lat=shared.fold.size
lat[lower.tri(lat)] <- NA
print(levelplot(lat,col.regions = clrs,xlab = "",ylab = "",colorkey = TRUE))

```

Now by absolute value:

```{r generate matrixabs}
thresh=0.05


shared.fold.size=matrix(NA,nrow = ncol(lfsr.mash),ncol=ncol(lfsr.mash))
colnames(shared.fold.size)=rownames(shared.fold.size)=colnames(lfsr.mash)
for(i in 1:ncol(lfsr.mash)){
  for(j in 1:ncol(lfsr.mash)){
    sig.row=which(lfsr.mash[,i]<thresh)
    sig.col=which(lfsr.mash[,j]<thresh)
    a=(union(sig.row,sig.col))
    #a=(intersect(sig.row,sig.col))
    #quotient=abs(pm.mash.beta[a,i]/pm.mash.beta[a,j])
    quotient=abs(pm.mash.beta[a,i]/pm.mash.beta[a,j])##divide effect sizes
    ##divide effect sizes
    shared.fold.size[i,j]=mean(quotient>0.5&quotient<2)
   
  }}

```


Here's if we do by absolute value:


```{r}


library(lattice)


clrs <- colorRampPalette(rev(c("#D73027","#FC8D59","#FEE090","#FFFFBF",
                               "#E0F3F8","#91BFDB","#4575B4")))(64)

lat=shared.fold.size
lat[lower.tri(lat)] <- NA
print(levelplot(lat,col.regions = clrs,xlab = "",ylab = "",colorkey = TRUE))

```


Now by significancs

```{r generate,echo}
thresh=0.05


shared.fold.size=matrix(NA,nrow = ncol(lfsr.mash),ncol=ncol(lfsr.mash))
colnames(shared.fold.size)=rownames(shared.fold.size)=colnames(lfsr.mash)
for(i in 1:ncol(lfsr.mash)){
  for(j in 1:ncol(lfsr.mash)){
    sig.row=which(lfsr.mash[,i]<thresh)
    sig.col=which(lfsr.mash[,j]<thresh)
    a=(union(sig.row,sig.col))
    #a=(intersect(sig.row,sig.col))
    #quotient=abs(pm.mash.beta[a,i]/pm.mash.beta[a,j])
    ##divide effect sizes
    shared.fold.size[i,j]=length(intersect(sig.row,sig.col))/length(a)
   
  }}

```


Here's if we do by absolute value:


```{r}


library(lattice)


clrs <- colorRampPalette(rev(c("#D73027","#FC8D59","#FEE090","#FFFFBF",
                               "#E0F3F8","#91BFDB","#4575B4")))(64)

lat=shared.fold.size
lat[lower.tri(lat)] <- NA
print(levelplot(lat,col.regions = clrs,xlab = "",ylab = "",colorkey = TRUE))

```


