---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


```{r}
setwd("~/lipids_mvp/analysis/")
source("../scripts/Sim_with_error.R")
#m.model=readRDS("../data/mashcomplete.rds")
m.model=readRDS("../data/mfitMVP.rds")
covmat=m.model$fitted_g$Ulist[1:7]
set.seed(123)
sim.data=sim.with.error(J=10000,d=4,rho=0.0,n=0,covmat = covmat,betasd = 0.0001,esd = 0.005) ##sample 100 from the K covariance matrices with equal probability

bmat=sim.data$betahat
semat=sim.data$sebetahat

beta=sim.data$beta

zmat=bmat/semat


```

Here we demonstrate the correlated error matrix:

```{r}
zmash=zmat
library("mashr")
library("flashr")
source('~/Dropbox/jointData/flashscript.R')
# identify a random subset of 20000 tests
random.subset = sample(1:nrow(zmash),2000)

data.temp = mash_set_data(zmash[random.subset,],alpha = 1)
Vhat = estimate_null_correlation_simple(data.temp)
#Vhat=diag(rep(1,4))
library("lattice")
clrs = colorRampPalette((c("#D73027","#FC8D59","#FEE090","#FFFFBF", "#E0F3F8","#91BFDB","#4575B4")))(64)

print(levelplot(Vhat,col.regions = clrs,xlab = "",ylab = "",colorkey = TRUE,main="VHAT"))

rm(data.temp)
data.random = mash_set_data(zmash[random.subset,],alpha = 1,V=Vhat)

maxval=apply(zmash,1,function(x){max(abs(x))})
zmax=zmash[order(maxval,decreasing = T),][1:100,]


data.strong = mash_set_data(zmax,alpha = 1,V=Vhat)

U.pca = cov_pca(data.strong,3)

U.flash=cov_flash(data.strong, non_canonical = TRUE)
X.center = apply(data.strong$Bhat, 2, function(x) x - mean(x))
U.ed = cov_ed(data.strong, c(U.flash, U.pca, list("XX" = t(X.center) %*% X.center / nrow(X.center))))
saveRDS(U.ed,"~/lipids_mvp/data/EDcov_sim_MVP.Rds")


U.ed=readRDS("~/lipids_mvp/data/EDcov_sim_MVP.Rds")
U.c = cov_canonical(data.random)
m = mash(data.random, Ulist = c(U.ed,U.c),outputlevel = 1)

mash.data=mash_set_data(zmash,V = Vhat,alpha = 1)

m$result=mash_compute_posterior_matrices(m, mash.data, algorithm.version = "Rcpp")
lfsr.mash=m$result$lfsr
saveRDS(m,"~/lipids_mvp/data/mashresult_sim_MVP.rds")
```

```{r plotting}

k=length(m$fitted_g$Ulist)
l=length(m$fitted_g$grid)
pimat=matrix(m$fitted_g$pi[-1],nrow=l,byrow=T)
colnames(pimat)=names(m$fitted_g$pi)[2:(k+1)]
barplot(colSums(pimat),las=2)

# library("lattice")
# for(i in 1:k){
#   z.num=as.matrix(cov2cor(m$fitted_g$Ulist[[i]]))
#   colnames(z.num)=row.names(z.num)=colnames(zmash)
# clrs = colorRampPalette((c("#D73027","#FC8D59","#FEE090","#FFFFBF", "#E0F3F8","#91BFDB","#4575B4")))(64)
# z.num[lower.tri(z.num)] = NA
# print(levelplot(z.num,col.regions = clrs,xlab = "",ylab = "",colorkey = TRUE,main=paste0(names(m$fitted_g$Ulist)[[i]])))
# }


ash.z=apply(zmash,2,function(x){ashr::ash(x,sebetahat = rep(1,length(x)))})
saveRDS(ash.z,"~/lipids_mvp/data/ash_sim.rds")
univariate.ash.pm=cbind(ash.z[[1]]$result$PosteriorMean,ash.z[[2]]$result$PosteriorMean,ash.z[[3]]$result$PosteriorMean,ash.z[[4]]$result$PosteriorMean)

lfsr.ash=cbind(ash.z[[1]]$result$lfsr,ash.z[[2]]$result$lfsr,ash.z[[3]]$result$lfsr,ash.z[[4]]$result$lfsr)


```

If we want to compare to eQTL bma, we use only canonical configurations:

```{r}

U.c = cov_canonical(mash.data)  
print(names(U.c))
```



```{r}
m.c = mash(mash.data, U.c)

bma.pm=m.c$result$PosteriorMean
lfsr.bma=m.c$result$lfsr
```

Now let's do some analysis;

```{r}
sum(beta!=0)

thresh=seq(0,0.20,by=0.01)
sig.mash=NULL
sig.ash=NULL
sig.bma=NULL

sig.mash=sapply(thresh,function(x){sum(lfsr.mash<x)})
sig.ash=sapply(thresh,function(x){sum(lfsr.ash<x)})
sig.bma=sapply(thresh,function(x){sum(lfsr.bma<x)})
plot(thresh,sig.mash,col="green",ylim=c(0,100),main="Number of FP",xlab="Threshold",type="l")
points(thresh,sig.ash,col="red",type="l")
points(thresh,sig.bma,col="blue",type="l")



```