---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

###IL 6

## R Markdown
```{r packageload,eval=F}
library("mashr")
source("~/Downloads/flashscript.R")
library("stringr")
library('data.table')
library("flashr")

```


```{r data.mutate,eval=F}

z=load("~/Dropbox/forZhi/eqtl_il1b_cluster.Rdata")
z=
a=data.frame(do.call(rbind, strsplit(z$VARIANT_ID, '_')))
chr=a[,1]
bp=a[,2]

zframe=data.frame("chr"=chr,"bp"=as.numeric(bp),z[,-1])
rownames(zframe)=z$VARIANT_ID


maxes=apply(zframe[,c(3:ncol(zframe))],1,function(x){max(abs(x))})##get max abs Z across phenotypes
znew=cbind(zframe,maxes)
saveRDS(znew,"~/Dropbox/forZhi/znew_Il6.rds")
```

Retrieve max Z per block

```{r pressure, eval=F}
max_block=data.frame(matrix(ncol = ncol(znew)+1, nrow = nrow(bed)))
colnames(max_block)=c(colnames(znew),"variant_name")


##load in LD blocks
bed=read.table("~/Dropbox//ld_chunk.bed")
bed$V1=do.call(rbind, strsplit(bed$V1, 'chr'))[,2]

for(i in 1:nrow(bed)){
  chr=bed[i,1]
  start=bed[i,2]
  stop=bed[i,3]
  in_chrom=znew[znew$chr==chr,]##extract those of the same
  goodguys=in_chrom[in_chrom$bp>start&in_chrom$bp<stop,]
 if(nrow(goodguys)>0) {
    z.max=which.max(goodguys[,"maxes"])
    z_good=goodguys[z.max,]
    } else {
      z_good=rep(0,ncol(max_block))
    }
  z_good=data.table(z_good,stringsAsFactors = T)
  z_good$chr=as.character(z_good$chr)
  z_good$variant_name=rownames(goodguys)[z.max]
  max_block[i,]=z_good
  print(i)
}

max_block=na.omit(max_block)
write.table(max_block,"~/Dropbox/forZhi/max_ld_block_Il6.txt")
```

```{r}
#install.packages("devtools")
library(devtools)
#install_github("stephenslab/flashr",build_vignettes = FALSE)
library("flashr")
source('~/Downloads//flashscript.R')

znew=readRDS("~/Dropbox/forZhi/znew_Il6.rds")
zmash=as.matrix(znew[,-c(1,2,ncol(znew))])
saveRDS(zmash,"~/Dropbox/forZhi/zmash_Il6.rds")
rm(znew)

# identify a random subset of 20000 tests
random.subset = sample(1:nrow(zmash),40000)
saveRDS(random.subset,"~/Dropbox/forZhi/randomsubset_Il6.rds")
random.subset=readRDS("~/Dropbox/forZhi//randomsubset_Il6.rds")

data.temp = mash_set_data(zmash[random.subset,],alpha = 1)
Vhat = estimate_null_correlation_simple(data.temp)##correlation matrix of the errors
saveRDS(Vhat,"~/Dropbox/forZhi/pqtl_Vhat_Il6.rds")
library("lattice")
clrs = colorRampPalette((c("#D73027","#FC8D59","#FEE090","#FFFFBF", "#E0F3F8","#91BFDB","#4575B4")))(64)

print(levelplot(Vhat,col.regions = clrs,xlab = "",ylab = "",colorkey = TRUE,main="VHAT"))

rm(data.temp)

library('mashr')
data.random = mash_set_data(zmash[random.subset,],alpha = 1,V=Vhat)##use for E(Z)model

max_block=read.table(("~/Dropbox/forZhi/max_ld_block_Il6.txt"))
zmax=apply(max_block[,c(3:(ncol(max_block)-2))],2,function(x){as.numeric(x)});rownames(zmax)=max_block$variant_name
data.strong = mash_set_data(zmax,alpha = 1,V=Vhat)

U.pca = cov_pca(data.strong,3)
U.flash=cov_flash(data.strong, non_canonical = TRUE)
X.center = apply(data.strong$Bhat, 2, function(x) x - mean(x))
U.ed = cov_ed(data.strong, c(U.pca,U.flash,list("XX" = t(X.center) %*% X.center / nrow(X.center))))
saveRDS(U.ed,"~/Dropbox/forZhi/EDcov_Il6.Rds")

U.c = cov_canonical(data.random)

m = mash(data.random, Ulist = c(U.ed,U.c),outputlevel = 1)
saveRDS(m,"~/Dropbox/forZhi/mfitpQTL_Il6.rds")

```

To compute posterior:

```{r,eval=F}


for(i in 0:4){
  start=i*2e6+1
  stop=(i+1)*2e6
  print(c(start,stop))
  library("mashr")
  mash.data=mash_set_data(zmash[start:stop,],V = Vhat,alpha = 1)
  p=mash_compute_posterior_matrices(m$fitted_g, mash.data, algorithm.version = "Rcpp")
  saveRDS(p,file = paste0("~/Dropbox/forZhi/mash_pqtl_il6_batch",i,".rds"))
}
  
i=5
start=i*2e6+1
stop=nrow(zmash)
print(c(start,stop))
library("mashr")
mash.data=mash_set_data(zmash[start:stop,],V = Vhat,alpha = 1)
p=mash_compute_posterior_matrices(m$fitted_g, mash.data, algorithm.version = "Rcpp")
saveRDS(p,file = paste0("~/Dropbox/forZhi/mash_pqtl_il6_batch",i,".rds"))

i=0
  file=readRDS(paste0("~/Dropbox/forZhi/mash_pqtl_il6_batch",i,".rds"))
  p=file$PosteriorMean
  lfsr=file$lfsr

for(i in 1:5){
  file=readRDS(paste0("~/Dropbox/forZhi/mash_pqtl_il6_batch",i,".rds"))
  pm=file$PosteriorMean
  lf=file$lfsr
  p=rbind(p,pm)
  lfsr=rbind(lfsr,lf)
}

saveRDS(p,"~/Dropbox/forZhi/mash_pqtl_il6_posterior_z.rds")
saveRDS(lfsr,"~/Dropbox/forZhi/mash_pqtl_il6_lfsr.rds")
rm(list=ls())`
```